### ISSUE TITLE
Show how close to passing an active proposal is ( if is not passing)

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/staked-celo-web-app#102]
Passing is not simple and depends on several factors

A) amount of locked gold that historically has voted on proposals
B) reaching quarum
C) specific contract methods have different threasholds.

**Comment by aaronmgdr** [comment]
This is a hard stretch goal

**Comment by nicolasbrugneaux** [comment]
This is cool but a "nice-to-have" and hard (according to @aaronmgdr )
