### ISSUE TITLE
User can't vote on a 2nd proposal (voting with 0 CELO)

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/staked-celo-web-app#156]
_Documenting bugs reported by @product-matt on [Slack](https://celo-org.slack.com/archives/C0508EV6N3E/p1690481299575569)_

- [x] Solution in https://github.com/celo-org/staked-celo-web-app/pull/150
- [x] QA: ~~@product-matt~~ @0xarthurxyz to confirm that bug is fixed for him

## Context 

> if I vote on one CGP, and then want to vote on a second one - cannot do it, just am shown 0 CELO (example screenshots for the 2 wallets i tried with - doesn’t work with either, on different browsers)

> i vote on one CGP. if i want to vote on another active one, it shows me that I can only vote with 0 CELO (although i have stCELO). it looks like it can only deploy these stCELO to one vote/CGP. However, I CAN vote with “0 CELO voting for…“. so I am not sure if just the UI is showing “voting with 0” but in the background it votes with correct balance, OR if it is voting actually with no weight

- @nicolasbrugneaux couldn't reproduce this error
- @aaronmgdr managed to reproduce this

<img width="350" alt="image" src="https://github.com/celo-org/staked-celo-web-app/assets/46296830/89f26759-e360-4750-9c46-aa86b604f740">

<img width="350" alt="image" src="https://github.com/celo-org/staked-celo-web-app/assets/46296830/7e0b9a26-b417-427d-8644-8c7b4ecd59b6">

**Comment by nicolasbrugneaux** [comment]
See 
- https://github.com/celo-org/staked-celo-web-app/issues/158 for resolution

It was merged and deployed with #161 #164

**Comment by 0xarthurxyz** [comment]
QA'ed by voting on both proposal 137 and 138. Works as expected (see recording):

https://github.com/celo-org/staked-celo-web-app/assets/46296830/c107e84a-c1f1-499d-8850-e0d9316ff861
