### ISSUE TITLE
Add Functionality to Better Manage Locked stCELO during CGP Voting

### ISSUE THREAD

**Issue by soloseng** [celo-org/staked-celo-web-app#158]
### Current Behavior

When a user votes on a governance proposal, their stCELO balance gets locked by the manager contract. This locked stCELO is not automatically unlocked after a proposal voting period has elapsed, and requires the user to manually unlock them.

While their stCELO balance is locked, a user cannot see that balance `stCELO.balanceOf(address)`, or transfer it. 

This behavior causes some user to think that their funds are missing.

### Expected Behavior

Show the currently voting(locked) stCELO balance to the users.

- Add a UI component that shows the current locked balance of a user by calling the view function `stCELO.lockedVoteBalanceOf(address)`

- Add a UI component that shows the locked stCELO currently being used to vote on a proposal. `vote.getLockedStCeloInVoting(address)`

- Add a UI component that allows the user to unlock their balance submitting `stCELO.unlockVoteBalance(address)` transaction.

**Comment by nicolasbrugneaux** [comment]
This was merged as part of #164 #161 
- @product-matt can you confirm you're happy with the results ?
