### ISSUE TITLE
Add Functionality to revoke/cancel CGP Votes

### ISSUE THREAD

**Issue by soloseng** [celo-org/staked-celo-web-app#160]
### Current Behavior
When a user has voted for a proposal, they are unable to cancel their votes using the UI.

### Expected Behavior

If a user voted on a proposal, they should be able to cancel their vote by interacting with the UI to send a transaction to the manager contract `manager.revokeVotes()`, allowing them to cancel their votes.

**Comment by nicolasbrugneaux** [comment]
@0xarthurxyz Proposing this as a good first issue for @yerdua, happy to pair and help on this.

**Comment by yerdua** [comment]
Are there any non-obvious conditions for revoking votes? I have a work in progress that adds a button, and seems to send the transaction.

WIP code: #180 
WIP demo: https://staked-celo-web-app-git-feat-revoke-cancel-cgp-votes-c-labs.vercel.app/governance/

One of the many transactions triggered by clicking this button: [0x631369b5d0b111f5efd43af2b1faf562fba4414c0faafdf23dd3f83507c98704](https://explorer.celo.org/mainnet/tx/0x631369b5d0b111f5efd43af2b1faf562fba4414c0faafdf23dd3f83507c98704)

As far as I can tell, the transaction looks correct and has been processed. However, the votes are unchanged.

**Comment by yerdua** [comment]
At the time of writing (2023-09-25), there are no longer any active CGPs on mainnet to test with. This is not high enough priority to jump through the hoops of setting up test conditions on alfajores, or mocking them otherwise. This is considered blocked until there's a CGP active on mainnet again.

**Comment by nicolasbrugneaux** [comment]
- PR Ready here #180
