### ISSUE TITLE
User cannot disconnect account

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/staked-celo-web-app#168]
Reproduce the bug:

- I connected a Safe wallet (app.safe.global) using WalletConnect. 
- I can't find a button to disconnect the wallet in the stcelo UI:
  <img src="https://github.com/celo-org/staked-celo-web-app/assets/46296830/b693fb18-b773-49a4-9f73-2d1b4063c24e" width="650">

- I disconnected in the Safe wallet, but the wallet is still connected in stcelo
- Re-loading the page doesn't fix this, the account is still connected.

**Comment by nicolasbrugneaux** [comment]
PR ready for review here: 
- https://github.com/celo-org/staked-celo-web-app/pull/170
