### ISSUE TITLE
Fix: clicking on Alfajores button does nothing

### ISSUE THREAD

**Issue by yerdua** [celo-org/staked-celo-web-app#177]
With a connected Valora wallet that's only been used on mainnet, clicking on the Alfajores button has no apparent affect in the UI. Each click results in an error in the console:

`Object { context: "client" }
 Missing or invalid. request() method: wallet_switchEthereumChain`

https://github.com/celo-org/staked-celo-web-app/assets/1222891/ac5d7626-9d83-4b77-ad40-68855f108078

**Comment by yerdua** [comment]
With a connected Valora wallet that's only been used on mainnet, clicking on the Alfajores button has no apparent affect in the UI. Each click results in an error in the console:

`Object { context: "client" }
 Missing or invalid. request() method: wallet_switchEthereumChain`

https://github.com/celo-org/staked-celo-web-app/assets/1222891/ac5d7626-9d83-4b77-ad40-68855f108078

**Comment by yerdua** [comment]
The Valora wallet used only supports mainnet. When a wallet doesn't support a network, this should be messaged to the user reasonably.

**Comment by 0xarthurxyz** [comment]
Sprint planning: This is a good onboarding ticket onto stCelo

**Comment by aaronmgdr** [comment]
quick handle the exception. (give feedback like 'this wallet doesnt suppot alfajores' )

better dont show
