### ISSUE TITLE
Frontend should display all governance proposals

### ISSUE THREAD

**Issue by martinvol** [celo-org/staked-celo-web-app#181]
# Current Behavior

stCelo is apparently only displaying rejected proposals.

<img width="772" alt="image" src="https://github.com/celo-org/staked-celo-web-app/assets/698027/fe315a04-0127-45b9-97f1-8d4eee1d96fa">

# Expected Behavior

All proposals should be included in the list, for example CGP 135 and CGP 136 are missing. It may not be trivial to retrieve passed proposals since they are removed on-chain once they pass. In that case I'd consider only showing in-fly proposals rather than a history.

**Comment by aaronmgdr** [comment]
celo station will have voting feature and part of req is to display historic proposals. so we could  potentially use same backend / learnings
