### ISSUE TITLE
Investigate stCELO "withdrawal" bug

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/staked-celo-web-app#200]
_Copy/pasting bug report from Daniel on [Slack](https://celo-org.slack.com/archives/C0508EV6N3E/p1705330613535579)_

> I am getting an error when I try to unstake on stCelo. I get a:
> 
> ```
> eth_signTransaction: Gas must be provided to sign a transaction
> ```
> 
> I do have CELO to pay for gas.
> this is a screenshot from the console:
> 
> <img width="390" alt="image" src="https://github.com/celo-org/staked-celo-web-app/assets/46296830/185763e3-6dd9-4aef-8d1f-b0715f5e4c4f">
> 
> we reviewed this error with @therealharpaljadeja and concluded it might be a FrontEnd Issue. @therealharpaljadeja also noticed that the contracts are not verified on Celoscan
```[tasklist]
### Tasks
- [ ] Verify stcelo contracts on celoscan.io
- [ ] Reproduce or understand bug
- [ ] Fix bug
```

**Comment by arthurgousset** [comment]
This might be caused by a known bug in the stcelo bot. The bug leads to failed activate, claim, and vote operations and occurs when there is a race condition in the bot. It looks like this race condition is becoming more frequent with more traffic.

More context and fix in this stcelo bot PR:
- https://github.com/celo-org/staked-celo-bot/pull/133

**Comment by pahor167** [comment]
> This might be caused by a known bug in the stcelo bot. The bug leads to failed activate, claim, and vote operations and occurs when there is a race condition in the bot. It looks like this race condition is becoming more frequent with more traffic.
> 
> More context and fix by @celo-org/primitives in this stcelo bot PR:
> 
> * [Nonce handling staked-celo-bot#133](https://github.com/celo-org/staked-celo-bot/pull/133)

This seems like problem with wallet or UI, since st-celo bot bug cause only the api call to revert but this looks like revert of original transaction in user's wallet.

**Comment by arthurgousset** [comment]
Thanks for chiming in @pahor167 !

**Comment by arthurgousset** [comment]
@therealharpaljadeja: If you think this problem originates in Celo Terminal, have you reached out to @zviadm in [zviadm/celoterminal](https://github.com/zviadm/celoterminal) yet?

**Comment by arthurgousset** [comment]
Feedback from zviad:
<img width="350" src="https://github.com/celo-org/staked-celo-web-app/assets/46296830/8ead5145-2544-4a82-8c1e-a858a2ab9fba">
