### ISSUE TITLE
Investigate eth_send vs eth_sign 

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/staked-celo-web-app#238]
Feedback from zviad:
<img width="350" src="https://github.com/celo-org/staked-celo-web-app/assets/46296830/8ead5145-2544-4a82-8c1e-a858a2ab9fba">

_Originally posted by @arthurgousset in https://github.com/celo-org/staked-celo-web-app/issues/200#issuecomment-1929529124_

**Comment by aaronmgdr** [comment]
noticing that we are using useContractWrite without usePrepareContractWrite whereas the docs recommend highluy using usePrepareContractWrite for wagmi 1.0

so we should we should use it or move to wagmi 2.0 where its no longer needed

**Comment by arthurgousset** [comment]
Nit: Is there a follow-up ticket on our backlog for 

> we should we should use it or move to wagmi 2.0 where its no longer needed 

So we don't forget?
