### ISSUE TITLE
Unstake issue

### ISSUE THREAD

**Issue by Bimasolana** [celo-org/staked-celo-web-app#245]
### Package

Unstake

### What wallet app are you using to connect?

Valora

### Browser

Chrome

### Describe the bug

![Screenshot_2024-04-15-15-15-52-89_c7dffd53562174b47a9774db1c148556](https://github.com/celo-org/staked-celo-web-app/assets/166216641/58b08608-c414-4343-b970-ce3686df6baf)

The contract function "withdraw" reverted with the following signature: 0x0d438664 Unable to decode signature "0x0d438664" as it was not found on the provided ABI. Make sure you are using the correct ABI and that the error exists on it. You can look up the decoded signature here: https://openchain.xyz/signatures?query=0x0d438664. Contract Call: address: 0x0239b96D10a434a56CC9E09383077A0490cF9398 function: withdraw(uint256 stCeloAmount) args: (29532990448375249535) sender: 0x6a5D38bB57cdAafF8557224D9E5103CE03175fe7 Docs: https://viem.sh/docs/contract/decodeErrorResult.html Version: viem@1.21.3

**Comment by soloseng** [comment]
@Bimasolana Thanks for submitting this issue.

Yesterday we released [this post](https://forum.celo.org/t/stcelo-minor-accounting-error/8382) that explains the issue and how to resolve it.

You will have to wait to vote on the next governance proposal, but this should fix your issue.

Closing this for now. Feel free to re-open if the issue persists
