### ISSUE TITLE
Unstaking has not occurred

### ISSUE THREAD

**Issue by Katamosu** [celo-org/staked-celo-web-app#251]
### Package

Unstake

### What wallet app are you using to connect?

Valora

### Browser

Safari

### Describe the bug

Good day to whomever is reading this.

 I had unstaking my stCELO from the DAPP and I haven’t received my CELO. Even after waiting three days I was not able to see the countdown even after my stCELO was sent to the burn wallet. This is the Tx Hash for the transaction. 0x6042dac2372c765524773ff7e1ff998758caee598f998645514ee43d61b9ba51
 
This is also the wallet that was used to burn the stCELO. 0x0000000000000000000000000000000000000000

Here are images of the transactions. 
![IMG_0628](https://github.com/celo-org/staked-celo-web-app/assets/170756731/eb748463-81f3-4fda-aae5-21909e48ba89)
![IMG_0629](https://github.com/celo-org/staked-celo-web-app/assets/170756731/92970148-d9a6-4b5a-a72f-bd641704a73c)
![IMG_0630](https://github.com/celo-org/staked-celo-web-app/assets/170756731/44091204-295b-4926-84c8-c7ba05f92918)
![IMG_0631](https://github.com/celo-org/staked-celo-web-app/assets/170756731/75140e5b-4312-4cfb-89ab-897ce9032b29)

**Comment by binghaiyi** [comment]
I also encountered the problem of not being able to unstake

**Comment by Katamosu** [comment]
> I also encountered the problem of not being able to unstake 

Yeah I hope we haven't lost our Celo honestly.

**Comment by binghaiyi** [comment]
> > 我还遇到了无法解除股份的问题> > 我还遇到了无法解除股份的问题>> 是的，我希望我们没有诚实地失去我们的Celo。>> 是的，我希望我们没有诚实地失去我们的Celo。yes

**Comment by soloseng** [comment]
Hi @Katamosu, are you still having this issue?

Did you use the stCELO webApp when withdrawing or did you send your transaction directly to the contract without connecting to the webapp?

It is recommended that you use the webApp UI when interacting with stCELO, as there are additional functions that needs to be called during the withdrawal process. [See deposit and withdrawal flow documentation.](https://docs.stcelo.xyz/deposit-and-withdrawal-flows)

I have manually processed [the transaction](https://celoscan.io/tx/0x62c885b3a7715a13395331ebcea2bc4ed3167791ed1c1ce1b543cd9032c3691e) on your behalf, based on the address provided above, so now you should be able to see the pending withdrawals that should unlock in 3 days.

In the future, please use the stCELO webApp UI, to avoid this issue.

**Comment by soloseng** [comment]
Closing as stale
