### ISSUE TITLE
check if using best balance while voting on governance

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/staked-celo-web-app#254]
there are several balanaces. stcelo, locked, lockedInVoting, etc. 

we should confirm that the one passed in while voting on governance proposals is in fact the best / right one to use.

**Comment by aaronmgdr** [comment]
the st celo bug we fixed had me wonder if we are using the correct balances when doing operations like governance proposal voting. 

for example, the stCelo balance is displayed as the amount that will vote for a proposal, and this is then converted to celo using the toCelo method on managerContract 

for the initial vote maybe this is fine. but if  for subsequent. I think we need to be using the lockedVoteBalance

**Comment by nicolasbrugneaux** [comment]
Looking at https://github.com/celo-org/staked-celo/blob/master/contracts/Vote.sol#L252-L253, it became clear we're using the wrong logic to vote. Will upload a fix asap
