### ISSUE TITLE
Unstaked celo hasn't disbursed to wallet

### ISSUE THREAD

**Issue by fs107** [celo-org/staked-celo-web-app#271]
### Package

Unstake

### What wallet app are you using to connect?

Valora

### Browser

Chrome

### Describe the bug

I can't remember if I unstaked via the webapp in Valora or through Chome.

The transaction started on 25 Nov 2024 but I still haven't received the amount in my wallet. The celoscan transaction: 0xe0379d00de50a297e5638267dc9b42994b5b79b72dc27353b2013c0ff414040f

**Comment by Susankaten** [comment]
> ### Package
> Unstake
> 
> ### What wallet app are you using to connect?
> Valora
> 
> ### Browser
> Chrome
> 
> ### Describe the bug
> I can't remember if I unstaked via the webapp in Valora or through Chome.
> 
> The transaction started on 25 Nov 2024 but I still haven't received the amount in my wallet. The celoscan transaction: 0xe0379d00de50a297e5638267dc9b42994b5b79b72dc27353b2013c0ff414040f

Hello @fs107 
You are experiencing the transcript error,
It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID COL120917
Please see the link below to our dedicated support line:
[Celo Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Hinted-tech** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Celo Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> ### Package
> Unstake
> 
> ### What wallet app are you using to connect?
> Valora
> 
> ### Browser
> Chrome
> 
> ### Describe the bug
> I can't remember if I unstaked via the webapp in Valora or through Chome.
> 
> The transaction started on 25 Nov 2024 but I still haven't received the amount in my wallet. The celoscan transaction: 0xe0379d00de50a297e5638267dc9b42994b5b79b72dc27353b2013c0ff414040f

**Comment by Daniellenero** [comment]
> ### Package
> Unstake
> 
> ### What wallet app are you using to connect?
> Valora
> 
> ### Browser
> Chrome
> 
> ### Describe the bug
> I can't remember if I unstaked via the webapp in Valora or through Chome.
> 
> The transaction started on 25 Nov 2024 but I still haven't received the amount in my wallet. The celoscan transaction: 0xe0379d00de50a297e5638267dc9b42994b5b79b72dc27353b2013c0ff414040f


Hello @fs107 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID CEL128509 for recovery guidelines. 
Please use the following link to access our dedicated support line: 
[Celo Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards

**Comment by martinvol** [comment]
Have you tried to go to the web dapp and click the "Claim" button?

**Comment by fs107** [comment]
I don't see a claim button! I checked on Chrome and via the Valora app
![Screenshot 2024-12-09 1 11 26 PM](https://github.com/user-attachments/assets/3c354d3c-d368-4c78-8d7b-a3535b9314ee)

**Comment by biotq23DE** [comment]
> Hi Martín, I don't see a claim button! I checked on Chrome and via the Valora app ![Screenshot 2024-12-09 1 11 26 PM](https://private-user-images.githubusercontent.com/190532873/393909482-3c354d3c-d368-4c78-8d7b-a3535b9314ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NjEyMzQsIm5iZiI6MTczMzc2MDkzNCwicGF0aCI6Ii8xOTA1MzI4NzMvMzkzOTA5NDgyLTNjMzU0ZDNjLWQzNjgtNGM3OC04ZDdiLWEzNTM1YjkzMTRlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxNjE1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzQwNTJhZWM5N2RjNmI5NTk5MDg1OTQyZTg5NWE4YzRhNmM1MTI4OWNmZmYzMTdhODNmN2VlYTUyNWUxMjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ecfngA_7ktp8uz2toAgOeFT6hhajHUM5GIosL-mgp0M)

Thank you for contacting us. We have logged your complaint regarding your recent service experience with ticket ID #CELO1456. For the fastest resolution, please use our 24/7 live chat support here:

[Celo Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

**Comment by soloseng** [comment]
> Hi Martín, I don't see a claim button! I checked on Chrome and via the Valora app ![Screenshot 2024-12-09 1 11 26 PM](https://private-user-images.githubusercontent.com/190532873/393909482-3c354d3c-d368-4c78-8d7b-a3535b9314ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NjExMDgsIm5iZiI6MTczMzc2MDgwOCwicGF0aCI6Ii8xOTA1MzI4NzMvMzkzOTA5NDgyLTNjMzU0ZDNjLWQzNjgtNGM3OC04ZDdiLWEzNTM1YjkzMTRlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxNjEzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2Q2NmE4ZWFhZTBmNTA2OWNhZGRmMmVlMjE4ODcwMTFhNGI1MzFkMTIwMmY5OGRkYWNiZTViYTgxYmFlZjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Q2eQb0e_0FfqKv5bPiLa7as-DzgFv9nq02fVOiNkRtE)

We had an interruption in service on the day you made the withdrawal, which caused your withdrawal to not have been processed immediately. I just re submitted your request based on the address of in the TX hash you shared. If you navigate to the stCELO webApp now, you should see that you have pending withdrawals that will be ready to claim in 3 days (Fri Dec 13 2024 21:40:23 GMT+0000).

**Comment by fs107** [comment]
@soloseng I see the update, thank you so much.

I will update you guys on Friday.

**Comment by fs107** [comment]
Hi all, the unstaking went through successfully. Thank you for your help I will close this ticket.
