### ISSUE TITLE
Enable Expert Mode Toggle

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/staked-celo-web-app#92]
Expert Mode Toggle 

top right of app 

Store the state in top level reducer/

Will be used to determine if select validator and vote pages are shown. but building them is not part of this ticket. 

![Image](https://user-images.githubusercontent.com/3814795/225991350-9deb69e9-54c0-4a56-9a79-6c07848fb703.png)

**Comment by nicolasbrugneaux** [comment]
It seems clicking the gear icon and then toggling and "expert mode" seems nonsensical if there is only 1 option available.

Options:
- keep it as is and clicking the gear shows a modal
- forget the gear icon and have a toggle somewhere on the page
- forget the expert mode

@product-matt what do you think?

**Comment by product-matt** [comment]
@nicolasbrugneaux  agreed. let's forget expert mode and just add these two new "tabs" and show them always

**Comment by nicolasbrugneaux** [comment]
👍
