### ISSUE TITLE
Ability to vote on active proposals

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/staked-celo-web-app#93]
For Proposals that are active (defined as in the stage where voting is possible) 

Show buttons for voting YES NO or Abstain. 

These should call the vote method on the StakedCelo Vote Contract. which requires setting the 

proposal Id 
index 
yes no and abstain vote counts. 

Note the contract allows voting both yes and no and obstain however UI will require going all in on one.

**Comment by aaronmgdr** [comment]
visually show title that links to github page

**Comment by nicolasbrugneaux** [comment]
![Image](https://user-images.githubusercontent.com/3650621/228585341-2b32b83e-3eee-4067-8dfe-fa442d19b359.png)
