### ISSUE TITLE
Add a new tab “Vote”

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/staked-celo-web-app#94]
* only viewable / navigatible while [Expert Mode is On](https://github.com/celo-org/staked-celo-web-app/issues/92)
* for reference stake and unstake are current tabs

 This will be where users go to Vote on Governance Proposals.

**Comment by nicolasbrugneaux** [comment]
![Image](https://user-images.githubusercontent.com/3650621/228585403-a438c5cf-13d8-488d-8da5-90bfbf085e12.png)
