### ISSUE TITLE
Show Proposals on the Vote page

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/staked-celo-web-app#95]
On the Page/tab created by #94

Should Include Info such as 

* Name 
* Link
* Votes received 

https://github.com/celo-org/staked-celo-web-app/issues/92 covers creating page

(see issue #93  and #96  for specifics on active and past proposals

Proposals are on the core Contracts not stCelo Contracts. 

See governance hack app for how to fetch proposals

**Comment by aaronmgdr** [comment]
see https://www.figma.com/file/CoSqsVIW9tYuJh6Cbji5d6/stCelo-elections?node-id=0-1&t=kqVuomh0t4PZNhlp-0

**Comment by nicolasbrugneaux** [comment]
![Image](https://user-images.githubusercontent.com/3650621/228585180-70cb7139-0a1a-4776-8a0a-83580b7124a0.png)
![Image](https://user-images.githubusercontent.com/3650621/228585181-5dc9ef5d-75b4-4bc5-a083-868317d0f620.png)
