### ISSUE TITLE
Past Proposals View

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/staked-celo-web-app#96]
As well as the standard proposals info 

Past proposals should 

* show if they passed or failed
* be clearly not active.

**Comment by nicolasbrugneaux** [comment]
It's a nice stretch goal depending on how fast we get the other tickets done

**Comment by nicolasbrugneaux** [comment]
![Image](https://user-images.githubusercontent.com/3650621/228585259-3301ff61-0c17-4c2a-ac5b-c59c190d924b.png)

**Comment by 0xarthurxyz** [comment]
Sprint planning (Wed, Mar 29):
- This is not necessarily in the MVP scope (but cool to have)
